// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameAuthTokenLog = "auth_token_log"

// AuthTokenLog mapped from table <auth_token_log>
type AuthTokenLog struct {
	ID            int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	TokenID       int64      `gorm:"column:token_id;not null;index:idx_auth_token_log_token_id,priority:1;default:0" json:"tokenId" form:"tokenId"`
	UID           int64      `gorm:"column:uid;not null;index:idx_auth_token_log_uid,priority:1;default:0" json:"uid" form:"uid"`
	Protocol      string     `gorm:"column:protocol;not null;default:''" json:"protocol" form:"protocol"`
	Client        string     `gorm:"column:client;not null;default:''" json:"client" form:"client"`
	ClientName    string     `gorm:"column:client_name;default:''" json:"clientName" form:"clientName"`
	ClientVersion string     `gorm:"column:client_version;default:''" json:"clientVersion" form:"clientVersion"`
	IP            string     `gorm:"column:ip;default:''" json:"ip" form:"ip"`
	Ua            string     `gorm:"column:ua;default:''" json:"ua" form:"ua"`
	StatusCode    int64      `gorm:"column:status_code;default:0" json:"statusCode" form:"statusCode"`
	CreatedAt     timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
}

// TableName AuthTokenLog's table name
func (*AuthTokenLog) TableName() string {
	return TableNameAuthTokenLog
}
