// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID               int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	VaultID          int64      `gorm:"column:vault_id;not null;index:idx_file_vault_id_path,priority:1;index:idx_file_vault_id_updated_timestamp,priority:1;index:idx_file_vault_id_updated_at,priority:1;index:idx_file_vault_id_rename,priority:1;index:idx_file_vault_id_action_rename,priority:1;index:idx_file_vault_id_path_hash,priority:1;index:idx_file_vault_id_action_fid,priority:1;default:0" json:"vaultId" form:"vaultId"`
	Action           string     `gorm:"column:action;type:varchar(255);index:idx_file_vault_id_action_rename,priority:2;index:idx_file_vault_id_action_fid,priority:2;default:''" json:"action" form:"action"`
	FID              int64      `gorm:"column:fid;index:idx_file_vault_id_action_fid,priority:3;default:0" json:"fid" form:"fid"`
	Path             string     `gorm:"column:path;type:varchar(255);index:idx_file_vault_id_path,priority:2;default:''" json:"path" form:"path"`
	PathHash         string     `gorm:"column:path_hash;type:varchar(255);index:idx_file_vault_id_path_hash,priority:2;default:''" json:"pathHash" form:"pathHash"`
	ContentHash      string     `gorm:"column:content_hash;default:''" json:"contentHash" form:"contentHash"`
	SavePath         string     `gorm:"column:save_path;default:''" json:"savePath" form:"savePath"`
	Rename           int64      `gorm:"column:rename;index:idx_file_vault_id_rename,priority:2;index:idx_file_vault_id_action_rename,priority:3;default:0" json:"rename" form:"rename"`
	Size             int64      `gorm:"column:size;not null;default:0" json:"size" form:"size"`
	Ctime            int64      `gorm:"column:ctime;not null;default:0" json:"ctime" form:"ctime"`
	Mtime            int64      `gorm:"column:mtime;not null;default:0" json:"mtime" form:"mtime"`
	UpdatedTimestamp int64      `gorm:"column:updated_timestamp;not null;index:idx_file_vault_id_updated_timestamp,priority:2;default:0" json:"updatedTimestamp" form:"updatedTimestamp"`
	CreatedAt        timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt        timex.Time `gorm:"column:updated_at;index:idx_file_vault_id_updated_at,priority:2;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
