// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/haierkeys/fast-note-sync-service/pkg/timex"
)

const TableNameGitSyncHistory = "git_sync_history"

// GitSyncHistory mapped from table <git_sync_history>
type GitSyncHistory struct {
	ID        int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	UID       int64      `gorm:"column:uid;not null;index:idx_git_sync_history_uid,priority:1;default:0" json:"uid" form:"uid"`
	ConfigID  int64      `gorm:"column:config_id;not null;index:idx_git_sync_history_config_id,priority:1;default:0" json:"configId" form:"configId"`
	StartTime time.Time  `gorm:"column:start_time" json:"startTime" form:"startTime"`
	EndTime   time.Time  `gorm:"column:end_time" json:"endTime" form:"endTime"`
	Status    int64      `gorm:"column:status;default:0" json:"status" form:"status"`
	Message   string     `gorm:"column:message;type:TEXT;default:''" json:"message" form:"message"`
	CreatedAt timex.Time `gorm:"column:created_at;index:idx_git_sync_history_uid,priority:2;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt timex.Time `gorm:"column:updated_at;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
}

// TableName GitSyncHistory's table name
func (*GitSyncHistory) TableName() string {
	return TableNameGitSyncHistory
}
