// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameNoteHistory = "note_history"

// NoteHistory mapped from table <note_history>
type NoteHistory struct {
	ID          int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	NoteID      int64      `gorm:"column:note_id;not null;index:idx_note_history_content_hash,priority:1;index:idx_note_history_version,priority:1;index:idx_note_history_note_id,priority:1;default:0" json:"noteId" form:"noteId"`
	VaultID     int64      `gorm:"column:vault_id;not null;default:0" json:"vaultId" form:"vaultId"`
	Path        string     `gorm:"column:path;default:''" json:"path" form:"path"`
	Content     string     `gorm:"column:content;default:''" json:"content" form:"content"`
	ContentHash string     `gorm:"column:content_hash;type:varchar(255);not null;index:idx_note_history_content_hash,priority:2;default:''" json:"contentHash" form:"contentHash"`
	DiffPatch   string     `gorm:"column:diff_patch;default:''" json:"diffPatch" form:"diffPatch"`
	ClientName  string     `gorm:"column:client_name;default:''" json:"clientName" form:"clientName"`
	Version     int64      `gorm:"column:version;index:idx_note_history_version,priority:2;default:0" json:"version" form:"version"`
	CreatedAt   timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt   timex.Time `gorm:"column:updated_at;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
}

// TableName NoteHistory's table name
func (*NoteHistory) TableName() string {
	return TableNameNoteHistory
}
