// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameSchemaVersion = "schema_version"

// SchemaVersion mapped from table <schema_version>
type SchemaVersion struct {
	ID          int64      `gorm:"column:id;primaryKey;default:0" json:"id"`
	Version     string     `gorm:"column:version;not null;uniqueIndex:idx_schema_version_version,priority:1;default:''" json:"version"`
	Description string     `gorm:"column:description;default:''" json:"description"`
	AppliedAt   timex.Time `gorm:"column:applied_at;not null" json:"applied_at"`
}

// TableName SchemaVersion's table name
func (*SchemaVersion) TableName() string {
	return TableNameSchemaVersion
}
