// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameStorage = "storage"

// Storage mapped from table <storage>
type Storage struct {
	ID              int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	UID             int64      `gorm:"column:uid;not null;index:idx_storage_uid,priority:1;default:0" json:"uid" form:"uid"`
	Type            string     `gorm:"column:type;default:''" json:"type" form:"type"`
	Endpoint        string     `gorm:"column:endpoint;default:''" json:"endpoint" form:"endpoint"`
	Region          string     `gorm:"column:region;default:''" json:"region" form:"region"`
	AccountID       string     `gorm:"column:account_id;default:''" json:"accountId" form:"accountId"`
	BucketName      string     `gorm:"column:bucket_name;default:''" json:"bucketName" form:"bucketName"`
	AccessKeyID     string     `gorm:"column:access_key_id;default:''" json:"accessKeyId" form:"accessKeyId"`
	AccessKeySecret string     `gorm:"column:access_key_secret;default:''" json:"accessKeySecret" form:"accessKeySecret"`
	CustomPath      string     `gorm:"column:custom_path;default:''" json:"customPath" form:"customPath"`
	AccessURLPrefix string     `gorm:"column:access_url_prefix;default:''" json:"accessUrlPrefix" form:"accessUrlPrefix"`
	User            string     `gorm:"column:user;default:''" json:"user" form:"user"`
	Password        string     `gorm:"column:password;default:''" json:"password" form:"password"`
	IsEnabled       int64      `gorm:"column:is_enabled;not null;default:0" json:"isEnabled" form:"isEnabled"`
	IsDeleted       int64      `gorm:"column:is_deleted;not null;default:0" json:"isDeleted" form:"isDeleted"`
	CreatedAt       timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt       timex.Time `gorm:"column:updated_at;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
	DeletedAt       timex.Time `gorm:"column:deleted_at;default:NULL" json:"deletedAt" form:"deletedAt"`
}

// TableName Storage's table name
func (*Storage) TableName() string {
	return TableNameStorage
}
