// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameSyncLog = "sync_log"

// SyncLog mapped from table <sync_log>
type SyncLog struct {
	ID            int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	UID           int64      `gorm:"column:uid;not null;index:idx_sync_log_uid_type_action,priority:1;index:idx_sync_log_uid_created_at,priority:1;default:0" json:"uid" form:"uid"`
	VaultID       int64      `gorm:"column:vault_id;not null;default:0" json:"vaultId" form:"vaultId"`
	Type          string     `gorm:"column:type;type:varchar(255);not null;index:idx_sync_log_uid_type_action,priority:2;default:''" json:"type" form:"type"`
	Action        string     `gorm:"column:action;type:varchar(255);index:idx_sync_log_uid_type_action,priority:3;default:''" json:"action" form:"action"`
	ChangedFields string     `gorm:"column:changed_fields;type:TEXT;default:''" json:"changedFields" form:"changedFields"`
	Path          string     `gorm:"column:path;type:TEXT;default:''" json:"path" form:"path"`
	PathHash      string     `gorm:"column:path_hash;default:''" json:"pathHash" form:"pathHash"`
	Size          int64      `gorm:"column:size;default:0" json:"size" form:"size"`
	ClientName    string     `gorm:"column:client_name;default:''" json:"clientName" form:"clientName"`
	ClientType    string     `gorm:"column:client_type;default:''" json:"clientType" form:"clientType"`
	ClientVersion string     `gorm:"column:client_version;default:''" json:"clientVersion" form:"clientVersion"`
	Status        int64      `gorm:"column:status;default:1" json:"status" form:"status"`
	Message       string     `gorm:"column:message;type:TEXT;default:''" json:"message" form:"message"`
	CreatedAt     timex.Time `gorm:"column:created_at;index:idx_sync_log_uid_created_at,priority:2;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
}

// TableName SyncLog's table name
func (*SyncLog) TableName() string {
	return TableNameSyncLog
}
