// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID       int64      `gorm:"column:uid;primaryKey" json:"uid" form:"uid"`
	Email     string     `gorm:"column:email;index:idx_pre_user_email,priority:1;default:''" json:"email" form:"email"`
	Username  string     `gorm:"column:username;default:''" json:"username" form:"username"`
	Password  string     `gorm:"column:password;default:''" json:"password" form:"password"`
	Salt      string     `gorm:"column:salt;default:''" json:"salt" form:"salt"`
	Token     string     `gorm:"column:token;default:''" json:"token" form:"token"`
	Avatar    string     `gorm:"column:avatar;default:''" json:"avatar" form:"avatar"`
	IsDeleted int64      `gorm:"column:is_deleted;default:0" json:"isDeleted" form:"isDeleted"`
	UpdatedAt timex.Time `gorm:"column:updated_at;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
	CreatedAt timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	DeletedAt timex.Time `gorm:"column:deleted_at;default:NULL" json:"deletedAt" form:"deletedAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
