// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameVault = "vault"

// Vault mapped from table <vault>
type Vault struct {
	ID        int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	Vault     string     `gorm:"column:vault;type:varchar(255);index:idx_vault_uid,priority:1;default:''" json:"vault" form:"vault"`
	NoteCount int64      `gorm:"column:note_count;default:0" json:"noteCount" form:"noteCount"`
	NoteSize  int64      `gorm:"column:note_size;default:0" json:"noteSize" form:"noteSize"`
	FileCount int64      `gorm:"column:file_count;default:0" json:"fileCount" form:"fileCount"`
	FileSize  int64      `gorm:"column:file_size;default:0" json:"fileSize" form:"fileSize"`
	IsDeleted int64      `gorm:"column:is_deleted;default:0" json:"isDeleted" form:"isDeleted"`
	CreatedAt timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt timex.Time `gorm:"column:updated_at;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
}

// TableName Vault's table name
func (*Vault) TableName() string {
	return TableNameVault
}
