// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newAuthToken(db *gorm.DB, opts ...gen.DOOption) authToken {
	_authToken := authToken{}

	_authToken.authTokenDo.UseDB(db, opts...)
	_authToken.authTokenDo.UseModel(&model.AuthToken{})

	tableName := _authToken.authTokenDo.TableName()
	_authToken.ALL = field.NewAsterisk(tableName)
	_authToken.ID = field.NewInt64(tableName, "id")
	_authToken.UID = field.NewInt64(tableName, "uid")
	_authToken.TokenString = field.NewString(tableName, "token_string")
	_authToken.Scope = field.NewString(tableName, "scope")
	_authToken.ClientType = field.NewString(tableName, "client_type")
	_authToken.BoundIP = field.NewString(tableName, "bound_ip")
	_authToken.UserAgent = field.NewString(tableName, "user_agent")
	_authToken.Vaults = field.NewString(tableName, "vaults")
	_authToken.Status = field.NewInt64(tableName, "status")
	_authToken.IssueType = field.NewInt64(tableName, "issue_type")
	_authToken.LastUsedAt = field.NewTime(tableName, "last_used_at")
	_authToken.ExpiredAt = field.NewTime(tableName, "expired_at")
	_authToken.CreatedAt = field.NewField(tableName, "created_at")
	_authToken.UpdatedAt = field.NewField(tableName, "updated_at")

	_authToken.fillFieldMap()

	return _authToken
}

type authToken struct {
	authTokenDo authTokenDo

	ALL         field.Asterisk
	ID          field.Int64
	UID         field.Int64
	TokenString field.String
	Scope       field.String
	ClientType  field.String
	BoundIP     field.String
	UserAgent   field.String
	Vaults      field.String
	Status      field.Int64
	IssueType   field.Int64
	LastUsedAt  field.Time
	ExpiredAt   field.Time
	CreatedAt   field.Field
	UpdatedAt   field.Field

	fieldMap map[string]field.Expr
}

func (a authToken) Table(newTableName string) *authToken {
	a.authTokenDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authToken) As(alias string) *authToken {
	a.authTokenDo.DO = *(a.authTokenDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authToken) updateTableName(table string) *authToken {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.UID = field.NewInt64(table, "uid")
	a.TokenString = field.NewString(table, "token_string")
	a.Scope = field.NewString(table, "scope")
	a.ClientType = field.NewString(table, "client_type")
	a.BoundIP = field.NewString(table, "bound_ip")
	a.UserAgent = field.NewString(table, "user_agent")
	a.Vaults = field.NewString(table, "vaults")
	a.Status = field.NewInt64(table, "status")
	a.IssueType = field.NewInt64(table, "issue_type")
	a.LastUsedAt = field.NewTime(table, "last_used_at")
	a.ExpiredAt = field.NewTime(table, "expired_at")
	a.CreatedAt = field.NewField(table, "created_at")
	a.UpdatedAt = field.NewField(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authToken) WithContext(ctx context.Context) IAuthTokenDo {
	return a.authTokenDo.WithContext(ctx)
}

func (a authToken) TableName() string { return a.authTokenDo.TableName() }

func (a authToken) Alias() string { return a.authTokenDo.Alias() }

func (a authToken) Columns(cols ...field.Expr) gen.Columns { return a.authTokenDo.Columns(cols...) }

func (a *authToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authToken) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["uid"] = a.UID
	a.fieldMap["token_string"] = a.TokenString
	a.fieldMap["scope"] = a.Scope
	a.fieldMap["client_type"] = a.ClientType
	a.fieldMap["bound_ip"] = a.BoundIP
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["vaults"] = a.Vaults
	a.fieldMap["status"] = a.Status
	a.fieldMap["issue_type"] = a.IssueType
	a.fieldMap["last_used_at"] = a.LastUsedAt
	a.fieldMap["expired_at"] = a.ExpiredAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authToken) clone(db *gorm.DB) authToken {
	a.authTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authToken) replaceDB(db *gorm.DB) authToken {
	a.authTokenDo.ReplaceDB(db)
	return a
}

type authTokenDo struct{ gen.DO }

type IAuthTokenDo interface {
	gen.SubQuery
	Debug() IAuthTokenDo
	WithContext(ctx context.Context) IAuthTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthTokenDo
	WriteDB() IAuthTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthTokenDo
	Not(conds ...gen.Condition) IAuthTokenDo
	Or(conds ...gen.Condition) IAuthTokenDo
	Select(conds ...field.Expr) IAuthTokenDo
	Where(conds ...gen.Condition) IAuthTokenDo
	Order(conds ...field.Expr) IAuthTokenDo
	Distinct(cols ...field.Expr) IAuthTokenDo
	Omit(cols ...field.Expr) IAuthTokenDo
	Join(table schema.Tabler, on ...field.Expr) IAuthTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthTokenDo
	Group(cols ...field.Expr) IAuthTokenDo
	Having(conds ...gen.Condition) IAuthTokenDo
	Limit(limit int) IAuthTokenDo
	Offset(offset int) IAuthTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthTokenDo
	Unscoped() IAuthTokenDo
	Create(values ...*model.AuthToken) error
	CreateInBatches(values []*model.AuthToken, batchSize int) error
	Save(values ...*model.AuthToken) error
	First() (*model.AuthToken, error)
	Take() (*model.AuthToken, error)
	Last() (*model.AuthToken, error)
	Find() ([]*model.AuthToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthToken, err error)
	FindInBatches(result *[]*model.AuthToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthTokenDo
	Assign(attrs ...field.AssignExpr) IAuthTokenDo
	Joins(fields ...field.RelationField) IAuthTokenDo
	Preload(fields ...field.RelationField) IAuthTokenDo
	FirstOrInit() (*model.AuthToken, error)
	FirstOrCreate() (*model.AuthToken, error)
	FindByPage(offset int, limit int) (result []*model.AuthToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authTokenDo) Debug() IAuthTokenDo {
	return a.withDO(a.DO.Debug())
}

func (a authTokenDo) WithContext(ctx context.Context) IAuthTokenDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authTokenDo) ReadDB() IAuthTokenDo {
	return a.Clauses(dbresolver.Read)
}

func (a authTokenDo) WriteDB() IAuthTokenDo {
	return a.Clauses(dbresolver.Write)
}

func (a authTokenDo) Session(config *gorm.Session) IAuthTokenDo {
	return a.withDO(a.DO.Session(config))
}

func (a authTokenDo) Clauses(conds ...clause.Expression) IAuthTokenDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authTokenDo) Returning(value interface{}, columns ...string) IAuthTokenDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authTokenDo) Not(conds ...gen.Condition) IAuthTokenDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authTokenDo) Or(conds ...gen.Condition) IAuthTokenDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authTokenDo) Select(conds ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authTokenDo) Where(conds ...gen.Condition) IAuthTokenDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authTokenDo) Order(conds ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authTokenDo) Distinct(cols ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authTokenDo) Omit(cols ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authTokenDo) Join(table schema.Tabler, on ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authTokenDo) Group(cols ...field.Expr) IAuthTokenDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authTokenDo) Having(conds ...gen.Condition) IAuthTokenDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authTokenDo) Limit(limit int) IAuthTokenDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authTokenDo) Offset(offset int) IAuthTokenDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthTokenDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authTokenDo) Unscoped() IAuthTokenDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authTokenDo) Create(values ...*model.AuthToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authTokenDo) CreateInBatches(values []*model.AuthToken, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authTokenDo) Save(values ...*model.AuthToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authTokenDo) First() (*model.AuthToken, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthToken), nil
	}
}

func (a authTokenDo) Take() (*model.AuthToken, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthToken), nil
	}
}

func (a authTokenDo) Last() (*model.AuthToken, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthToken), nil
	}
}

func (a authTokenDo) Find() ([]*model.AuthToken, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthToken), err
}

func (a authTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthToken, err error) {
	buf := make([]*model.AuthToken, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authTokenDo) FindInBatches(result *[]*model.AuthToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authTokenDo) Attrs(attrs ...field.AssignExpr) IAuthTokenDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authTokenDo) Assign(attrs ...field.AssignExpr) IAuthTokenDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authTokenDo) Joins(fields ...field.RelationField) IAuthTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authTokenDo) Preload(fields ...field.RelationField) IAuthTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authTokenDo) FirstOrInit() (*model.AuthToken, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthToken), nil
	}
}

func (a authTokenDo) FirstOrCreate() (*model.AuthToken, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthToken), nil
	}
}

func (a authTokenDo) FindByPage(offset int, limit int) (result []*model.AuthToken, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authTokenDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authTokenDo) Delete(models ...*model.AuthToken) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authTokenDo) withDO(do gen.Dao) *authTokenDo {
	a.DO = *do.(*gen.DO)
	return a
}
