// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newAuthTokenLog(db *gorm.DB, opts ...gen.DOOption) authTokenLog {
	_authTokenLog := authTokenLog{}

	_authTokenLog.authTokenLogDo.UseDB(db, opts...)
	_authTokenLog.authTokenLogDo.UseModel(&model.AuthTokenLog{})

	tableName := _authTokenLog.authTokenLogDo.TableName()
	_authTokenLog.ALL = field.NewAsterisk(tableName)
	_authTokenLog.ID = field.NewInt64(tableName, "id")
	_authTokenLog.TokenID = field.NewInt64(tableName, "token_id")
	_authTokenLog.UID = field.NewInt64(tableName, "uid")
	_authTokenLog.Protocol = field.NewString(tableName, "protocol")
	_authTokenLog.Client = field.NewString(tableName, "client")
	_authTokenLog.ClientName = field.NewString(tableName, "client_name")
	_authTokenLog.ClientVersion = field.NewString(tableName, "client_version")
	_authTokenLog.IP = field.NewString(tableName, "ip")
	_authTokenLog.Ua = field.NewString(tableName, "ua")
	_authTokenLog.StatusCode = field.NewInt64(tableName, "status_code")
	_authTokenLog.CreatedAt = field.NewField(tableName, "created_at")

	_authTokenLog.fillFieldMap()

	return _authTokenLog
}

type authTokenLog struct {
	authTokenLogDo authTokenLogDo

	ALL           field.Asterisk
	ID            field.Int64
	TokenID       field.Int64
	UID           field.Int64
	Protocol      field.String
	Client        field.String
	ClientName    field.String
	ClientVersion field.String
	IP            field.String
	Ua            field.String
	StatusCode    field.Int64
	CreatedAt     field.Field

	fieldMap map[string]field.Expr
}

func (a authTokenLog) Table(newTableName string) *authTokenLog {
	a.authTokenLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authTokenLog) As(alias string) *authTokenLog {
	a.authTokenLogDo.DO = *(a.authTokenLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authTokenLog) updateTableName(table string) *authTokenLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.TokenID = field.NewInt64(table, "token_id")
	a.UID = field.NewInt64(table, "uid")
	a.Protocol = field.NewString(table, "protocol")
	a.Client = field.NewString(table, "client")
	a.ClientName = field.NewString(table, "client_name")
	a.ClientVersion = field.NewString(table, "client_version")
	a.IP = field.NewString(table, "ip")
	a.Ua = field.NewString(table, "ua")
	a.StatusCode = field.NewInt64(table, "status_code")
	a.CreatedAt = field.NewField(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *authTokenLog) WithContext(ctx context.Context) IAuthTokenLogDo {
	return a.authTokenLogDo.WithContext(ctx)
}

func (a authTokenLog) TableName() string { return a.authTokenLogDo.TableName() }

func (a authTokenLog) Alias() string { return a.authTokenLogDo.Alias() }

func (a authTokenLog) Columns(cols ...field.Expr) gen.Columns {
	return a.authTokenLogDo.Columns(cols...)
}

func (a *authTokenLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authTokenLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["token_id"] = a.TokenID
	a.fieldMap["uid"] = a.UID
	a.fieldMap["protocol"] = a.Protocol
	a.fieldMap["client"] = a.Client
	a.fieldMap["client_name"] = a.ClientName
	a.fieldMap["client_version"] = a.ClientVersion
	a.fieldMap["ip"] = a.IP
	a.fieldMap["ua"] = a.Ua
	a.fieldMap["status_code"] = a.StatusCode
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a authTokenLog) clone(db *gorm.DB) authTokenLog {
	a.authTokenLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authTokenLog) replaceDB(db *gorm.DB) authTokenLog {
	a.authTokenLogDo.ReplaceDB(db)
	return a
}

type authTokenLogDo struct{ gen.DO }

type IAuthTokenLogDo interface {
	gen.SubQuery
	Debug() IAuthTokenLogDo
	WithContext(ctx context.Context) IAuthTokenLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthTokenLogDo
	WriteDB() IAuthTokenLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthTokenLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthTokenLogDo
	Not(conds ...gen.Condition) IAuthTokenLogDo
	Or(conds ...gen.Condition) IAuthTokenLogDo
	Select(conds ...field.Expr) IAuthTokenLogDo
	Where(conds ...gen.Condition) IAuthTokenLogDo
	Order(conds ...field.Expr) IAuthTokenLogDo
	Distinct(cols ...field.Expr) IAuthTokenLogDo
	Omit(cols ...field.Expr) IAuthTokenLogDo
	Join(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo
	Group(cols ...field.Expr) IAuthTokenLogDo
	Having(conds ...gen.Condition) IAuthTokenLogDo
	Limit(limit int) IAuthTokenLogDo
	Offset(offset int) IAuthTokenLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthTokenLogDo
	Unscoped() IAuthTokenLogDo
	Create(values ...*model.AuthTokenLog) error
	CreateInBatches(values []*model.AuthTokenLog, batchSize int) error
	Save(values ...*model.AuthTokenLog) error
	First() (*model.AuthTokenLog, error)
	Take() (*model.AuthTokenLog, error)
	Last() (*model.AuthTokenLog, error)
	Find() ([]*model.AuthTokenLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthTokenLog, err error)
	FindInBatches(result *[]*model.AuthTokenLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthTokenLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthTokenLogDo
	Assign(attrs ...field.AssignExpr) IAuthTokenLogDo
	Joins(fields ...field.RelationField) IAuthTokenLogDo
	Preload(fields ...field.RelationField) IAuthTokenLogDo
	FirstOrInit() (*model.AuthTokenLog, error)
	FirstOrCreate() (*model.AuthTokenLog, error)
	FindByPage(offset int, limit int) (result []*model.AuthTokenLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthTokenLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authTokenLogDo) Debug() IAuthTokenLogDo {
	return a.withDO(a.DO.Debug())
}

func (a authTokenLogDo) WithContext(ctx context.Context) IAuthTokenLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authTokenLogDo) ReadDB() IAuthTokenLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a authTokenLogDo) WriteDB() IAuthTokenLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a authTokenLogDo) Session(config *gorm.Session) IAuthTokenLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a authTokenLogDo) Clauses(conds ...clause.Expression) IAuthTokenLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authTokenLogDo) Returning(value interface{}, columns ...string) IAuthTokenLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authTokenLogDo) Not(conds ...gen.Condition) IAuthTokenLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authTokenLogDo) Or(conds ...gen.Condition) IAuthTokenLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authTokenLogDo) Select(conds ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authTokenLogDo) Where(conds ...gen.Condition) IAuthTokenLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authTokenLogDo) Order(conds ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authTokenLogDo) Distinct(cols ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authTokenLogDo) Omit(cols ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authTokenLogDo) Join(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authTokenLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authTokenLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authTokenLogDo) Group(cols ...field.Expr) IAuthTokenLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authTokenLogDo) Having(conds ...gen.Condition) IAuthTokenLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authTokenLogDo) Limit(limit int) IAuthTokenLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authTokenLogDo) Offset(offset int) IAuthTokenLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authTokenLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthTokenLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authTokenLogDo) Unscoped() IAuthTokenLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authTokenLogDo) Create(values ...*model.AuthTokenLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authTokenLogDo) CreateInBatches(values []*model.AuthTokenLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authTokenLogDo) Save(values ...*model.AuthTokenLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authTokenLogDo) First() (*model.AuthTokenLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthTokenLog), nil
	}
}

func (a authTokenLogDo) Take() (*model.AuthTokenLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthTokenLog), nil
	}
}

func (a authTokenLogDo) Last() (*model.AuthTokenLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthTokenLog), nil
	}
}

func (a authTokenLogDo) Find() ([]*model.AuthTokenLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthTokenLog), err
}

func (a authTokenLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthTokenLog, err error) {
	buf := make([]*model.AuthTokenLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authTokenLogDo) FindInBatches(result *[]*model.AuthTokenLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authTokenLogDo) Attrs(attrs ...field.AssignExpr) IAuthTokenLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authTokenLogDo) Assign(attrs ...field.AssignExpr) IAuthTokenLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authTokenLogDo) Joins(fields ...field.RelationField) IAuthTokenLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authTokenLogDo) Preload(fields ...field.RelationField) IAuthTokenLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authTokenLogDo) FirstOrInit() (*model.AuthTokenLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthTokenLog), nil
	}
}

func (a authTokenLogDo) FirstOrCreate() (*model.AuthTokenLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthTokenLog), nil
	}
}

func (a authTokenLogDo) FindByPage(offset int, limit int) (result []*model.AuthTokenLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authTokenLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authTokenLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authTokenLogDo) Delete(models ...*model.AuthTokenLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authTokenLogDo) withDO(do gen.Dao) *authTokenLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
