// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newBackupConfig(db *gorm.DB, opts ...gen.DOOption) backupConfig {
	_backupConfig := backupConfig{}

	_backupConfig.backupConfigDo.UseDB(db, opts...)
	_backupConfig.backupConfigDo.UseModel(&model.BackupConfig{})

	tableName := _backupConfig.backupConfigDo.TableName()
	_backupConfig.ALL = field.NewAsterisk(tableName)
	_backupConfig.ID = field.NewInt64(tableName, "id")
	_backupConfig.UID = field.NewInt64(tableName, "uid")
	_backupConfig.VaultID = field.NewInt64(tableName, "vault_id")
	_backupConfig.Type = field.NewString(tableName, "type")
	_backupConfig.StorageIds = field.NewString(tableName, "storage_ids")
	_backupConfig.IsEnabled = field.NewInt64(tableName, "is_enabled")
	_backupConfig.CronStrategy = field.NewString(tableName, "cron_strategy")
	_backupConfig.CronExpression = field.NewString(tableName, "cron_expression")
	_backupConfig.IncludeVaultName = field.NewInt64(tableName, "include_vault_name")
	_backupConfig.RetentionDays = field.NewInt64(tableName, "retention_days")
	_backupConfig.LastRunTime = field.NewTime(tableName, "last_run_time")
	_backupConfig.NextRunTime = field.NewTime(tableName, "next_run_time")
	_backupConfig.LastStatus = field.NewInt64(tableName, "last_status")
	_backupConfig.LastMessage = field.NewString(tableName, "last_message")
	_backupConfig.PasswordMode = field.NewInt64(tableName, "password_mode")
	_backupConfig.PasswordValue = field.NewString(tableName, "password_value")
	_backupConfig.CreatedAt = field.NewField(tableName, "created_at")
	_backupConfig.UpdatedAt = field.NewField(tableName, "updated_at")

	_backupConfig.fillFieldMap()

	return _backupConfig
}

type backupConfig struct {
	backupConfigDo backupConfigDo

	ALL              field.Asterisk
	ID               field.Int64
	UID              field.Int64
	VaultID          field.Int64
	Type             field.String
	StorageIds       field.String
	IsEnabled        field.Int64
	CronStrategy     field.String
	CronExpression   field.String
	IncludeVaultName field.Int64
	RetentionDays    field.Int64
	LastRunTime      field.Time
	NextRunTime      field.Time
	LastStatus       field.Int64
	LastMessage      field.String
	PasswordMode     field.Int64
	PasswordValue    field.String
	CreatedAt        field.Field
	UpdatedAt        field.Field

	fieldMap map[string]field.Expr
}

func (b backupConfig) Table(newTableName string) *backupConfig {
	b.backupConfigDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b backupConfig) As(alias string) *backupConfig {
	b.backupConfigDo.DO = *(b.backupConfigDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *backupConfig) updateTableName(table string) *backupConfig {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.UID = field.NewInt64(table, "uid")
	b.VaultID = field.NewInt64(table, "vault_id")
	b.Type = field.NewString(table, "type")
	b.StorageIds = field.NewString(table, "storage_ids")
	b.IsEnabled = field.NewInt64(table, "is_enabled")
	b.CronStrategy = field.NewString(table, "cron_strategy")
	b.CronExpression = field.NewString(table, "cron_expression")
	b.IncludeVaultName = field.NewInt64(table, "include_vault_name")
	b.RetentionDays = field.NewInt64(table, "retention_days")
	b.LastRunTime = field.NewTime(table, "last_run_time")
	b.NextRunTime = field.NewTime(table, "next_run_time")
	b.LastStatus = field.NewInt64(table, "last_status")
	b.LastMessage = field.NewString(table, "last_message")
	b.PasswordMode = field.NewInt64(table, "password_mode")
	b.PasswordValue = field.NewString(table, "password_value")
	b.CreatedAt = field.NewField(table, "created_at")
	b.UpdatedAt = field.NewField(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *backupConfig) WithContext(ctx context.Context) IBackupConfigDo {
	return b.backupConfigDo.WithContext(ctx)
}

func (b backupConfig) TableName() string { return b.backupConfigDo.TableName() }

func (b backupConfig) Alias() string { return b.backupConfigDo.Alias() }

func (b backupConfig) Columns(cols ...field.Expr) gen.Columns {
	return b.backupConfigDo.Columns(cols...)
}

func (b *backupConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *backupConfig) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 18)
	b.fieldMap["id"] = b.ID
	b.fieldMap["uid"] = b.UID
	b.fieldMap["vault_id"] = b.VaultID
	b.fieldMap["type"] = b.Type
	b.fieldMap["storage_ids"] = b.StorageIds
	b.fieldMap["is_enabled"] = b.IsEnabled
	b.fieldMap["cron_strategy"] = b.CronStrategy
	b.fieldMap["cron_expression"] = b.CronExpression
	b.fieldMap["include_vault_name"] = b.IncludeVaultName
	b.fieldMap["retention_days"] = b.RetentionDays
	b.fieldMap["last_run_time"] = b.LastRunTime
	b.fieldMap["next_run_time"] = b.NextRunTime
	b.fieldMap["last_status"] = b.LastStatus
	b.fieldMap["last_message"] = b.LastMessage
	b.fieldMap["password_mode"] = b.PasswordMode
	b.fieldMap["password_value"] = b.PasswordValue
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b backupConfig) clone(db *gorm.DB) backupConfig {
	b.backupConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b backupConfig) replaceDB(db *gorm.DB) backupConfig {
	b.backupConfigDo.ReplaceDB(db)
	return b
}

type backupConfigDo struct{ gen.DO }

type IBackupConfigDo interface {
	gen.SubQuery
	Debug() IBackupConfigDo
	WithContext(ctx context.Context) IBackupConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBackupConfigDo
	WriteDB() IBackupConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBackupConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBackupConfigDo
	Not(conds ...gen.Condition) IBackupConfigDo
	Or(conds ...gen.Condition) IBackupConfigDo
	Select(conds ...field.Expr) IBackupConfigDo
	Where(conds ...gen.Condition) IBackupConfigDo
	Order(conds ...field.Expr) IBackupConfigDo
	Distinct(cols ...field.Expr) IBackupConfigDo
	Omit(cols ...field.Expr) IBackupConfigDo
	Join(table schema.Tabler, on ...field.Expr) IBackupConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBackupConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBackupConfigDo
	Group(cols ...field.Expr) IBackupConfigDo
	Having(conds ...gen.Condition) IBackupConfigDo
	Limit(limit int) IBackupConfigDo
	Offset(offset int) IBackupConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupConfigDo
	Unscoped() IBackupConfigDo
	Create(values ...*model.BackupConfig) error
	CreateInBatches(values []*model.BackupConfig, batchSize int) error
	Save(values ...*model.BackupConfig) error
	First() (*model.BackupConfig, error)
	Take() (*model.BackupConfig, error)
	Last() (*model.BackupConfig, error)
	Find() ([]*model.BackupConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupConfig, err error)
	FindInBatches(result *[]*model.BackupConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BackupConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBackupConfigDo
	Assign(attrs ...field.AssignExpr) IBackupConfigDo
	Joins(fields ...field.RelationField) IBackupConfigDo
	Preload(fields ...field.RelationField) IBackupConfigDo
	FirstOrInit() (*model.BackupConfig, error)
	FirstOrCreate() (*model.BackupConfig, error)
	FindByPage(offset int, limit int) (result []*model.BackupConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBackupConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b backupConfigDo) Debug() IBackupConfigDo {
	return b.withDO(b.DO.Debug())
}

func (b backupConfigDo) WithContext(ctx context.Context) IBackupConfigDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b backupConfigDo) ReadDB() IBackupConfigDo {
	return b.Clauses(dbresolver.Read)
}

func (b backupConfigDo) WriteDB() IBackupConfigDo {
	return b.Clauses(dbresolver.Write)
}

func (b backupConfigDo) Session(config *gorm.Session) IBackupConfigDo {
	return b.withDO(b.DO.Session(config))
}

func (b backupConfigDo) Clauses(conds ...clause.Expression) IBackupConfigDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b backupConfigDo) Returning(value interface{}, columns ...string) IBackupConfigDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b backupConfigDo) Not(conds ...gen.Condition) IBackupConfigDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b backupConfigDo) Or(conds ...gen.Condition) IBackupConfigDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b backupConfigDo) Select(conds ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b backupConfigDo) Where(conds ...gen.Condition) IBackupConfigDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b backupConfigDo) Order(conds ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b backupConfigDo) Distinct(cols ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b backupConfigDo) Omit(cols ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b backupConfigDo) Join(table schema.Tabler, on ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b backupConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b backupConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b backupConfigDo) Group(cols ...field.Expr) IBackupConfigDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b backupConfigDo) Having(conds ...gen.Condition) IBackupConfigDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b backupConfigDo) Limit(limit int) IBackupConfigDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b backupConfigDo) Offset(offset int) IBackupConfigDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b backupConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupConfigDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b backupConfigDo) Unscoped() IBackupConfigDo {
	return b.withDO(b.DO.Unscoped())
}

func (b backupConfigDo) Create(values ...*model.BackupConfig) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b backupConfigDo) CreateInBatches(values []*model.BackupConfig, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b backupConfigDo) Save(values ...*model.BackupConfig) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b backupConfigDo) First() (*model.BackupConfig, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupConfig), nil
	}
}

func (b backupConfigDo) Take() (*model.BackupConfig, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupConfig), nil
	}
}

func (b backupConfigDo) Last() (*model.BackupConfig, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupConfig), nil
	}
}

func (b backupConfigDo) Find() ([]*model.BackupConfig, error) {
	result, err := b.DO.Find()
	return result.([]*model.BackupConfig), err
}

func (b backupConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupConfig, err error) {
	buf := make([]*model.BackupConfig, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b backupConfigDo) FindInBatches(result *[]*model.BackupConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b backupConfigDo) Attrs(attrs ...field.AssignExpr) IBackupConfigDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b backupConfigDo) Assign(attrs ...field.AssignExpr) IBackupConfigDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b backupConfigDo) Joins(fields ...field.RelationField) IBackupConfigDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b backupConfigDo) Preload(fields ...field.RelationField) IBackupConfigDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b backupConfigDo) FirstOrInit() (*model.BackupConfig, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupConfig), nil
	}
}

func (b backupConfigDo) FirstOrCreate() (*model.BackupConfig, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupConfig), nil
	}
}

func (b backupConfigDo) FindByPage(offset int, limit int) (result []*model.BackupConfig, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b backupConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b backupConfigDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b backupConfigDo) Delete(models ...*model.BackupConfig) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *backupConfigDo) withDO(do gen.Dao) *backupConfigDo {
	b.DO = *do.(*gen.DO)
	return b
}
