// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newBackupHistory(db *gorm.DB, opts ...gen.DOOption) backupHistory {
	_backupHistory := backupHistory{}

	_backupHistory.backupHistoryDo.UseDB(db, opts...)
	_backupHistory.backupHistoryDo.UseModel(&model.BackupHistory{})

	tableName := _backupHistory.backupHistoryDo.TableName()
	_backupHistory.ALL = field.NewAsterisk(tableName)
	_backupHistory.ID = field.NewInt64(tableName, "id")
	_backupHistory.UID = field.NewInt64(tableName, "uid")
	_backupHistory.ConfigID = field.NewInt64(tableName, "config_id")
	_backupHistory.StorageID = field.NewInt64(tableName, "storage_id")
	_backupHistory.Type = field.NewString(tableName, "type")
	_backupHistory.StartTime = field.NewTime(tableName, "start_time")
	_backupHistory.EndTime = field.NewTime(tableName, "end_time")
	_backupHistory.Status = field.NewInt64(tableName, "status")
	_backupHistory.FileSize = field.NewInt64(tableName, "file_size")
	_backupHistory.FileCount = field.NewInt64(tableName, "file_count")
	_backupHistory.Message = field.NewString(tableName, "message")
	_backupHistory.FilePath = field.NewString(tableName, "file_path")
	_backupHistory.Password = field.NewString(tableName, "password")
	_backupHistory.CreatedAt = field.NewField(tableName, "created_at")
	_backupHistory.UpdatedAt = field.NewField(tableName, "updated_at")

	_backupHistory.fillFieldMap()

	return _backupHistory
}

type backupHistory struct {
	backupHistoryDo backupHistoryDo

	ALL       field.Asterisk
	ID        field.Int64
	UID       field.Int64
	ConfigID  field.Int64
	StorageID field.Int64
	Type      field.String
	StartTime field.Time
	EndTime   field.Time
	Status    field.Int64
	FileSize  field.Int64
	FileCount field.Int64
	Message   field.String
	FilePath  field.String
	Password  field.String
	CreatedAt field.Field
	UpdatedAt field.Field

	fieldMap map[string]field.Expr
}

func (b backupHistory) Table(newTableName string) *backupHistory {
	b.backupHistoryDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b backupHistory) As(alias string) *backupHistory {
	b.backupHistoryDo.DO = *(b.backupHistoryDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *backupHistory) updateTableName(table string) *backupHistory {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.UID = field.NewInt64(table, "uid")
	b.ConfigID = field.NewInt64(table, "config_id")
	b.StorageID = field.NewInt64(table, "storage_id")
	b.Type = field.NewString(table, "type")
	b.StartTime = field.NewTime(table, "start_time")
	b.EndTime = field.NewTime(table, "end_time")
	b.Status = field.NewInt64(table, "status")
	b.FileSize = field.NewInt64(table, "file_size")
	b.FileCount = field.NewInt64(table, "file_count")
	b.Message = field.NewString(table, "message")
	b.FilePath = field.NewString(table, "file_path")
	b.Password = field.NewString(table, "password")
	b.CreatedAt = field.NewField(table, "created_at")
	b.UpdatedAt = field.NewField(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *backupHistory) WithContext(ctx context.Context) IBackupHistoryDo {
	return b.backupHistoryDo.WithContext(ctx)
}

func (b backupHistory) TableName() string { return b.backupHistoryDo.TableName() }

func (b backupHistory) Alias() string { return b.backupHistoryDo.Alias() }

func (b backupHistory) Columns(cols ...field.Expr) gen.Columns {
	return b.backupHistoryDo.Columns(cols...)
}

func (b *backupHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *backupHistory) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 14)
	b.fieldMap["id"] = b.ID
	b.fieldMap["uid"] = b.UID
	b.fieldMap["config_id"] = b.ConfigID
	b.fieldMap["storage_id"] = b.StorageID
	b.fieldMap["type"] = b.Type
	b.fieldMap["start_time"] = b.StartTime
	b.fieldMap["end_time"] = b.EndTime
	b.fieldMap["status"] = b.Status
	b.fieldMap["file_size"] = b.FileSize
	b.fieldMap["file_count"] = b.FileCount
	b.fieldMap["message"] = b.Message
	b.fieldMap["file_path"] = b.FilePath
	b.fieldMap["password"] = b.Password
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b backupHistory) clone(db *gorm.DB) backupHistory {
	b.backupHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b backupHistory) replaceDB(db *gorm.DB) backupHistory {
	b.backupHistoryDo.ReplaceDB(db)
	return b
}

type backupHistoryDo struct{ gen.DO }

type IBackupHistoryDo interface {
	gen.SubQuery
	Debug() IBackupHistoryDo
	WithContext(ctx context.Context) IBackupHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBackupHistoryDo
	WriteDB() IBackupHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBackupHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBackupHistoryDo
	Not(conds ...gen.Condition) IBackupHistoryDo
	Or(conds ...gen.Condition) IBackupHistoryDo
	Select(conds ...field.Expr) IBackupHistoryDo
	Where(conds ...gen.Condition) IBackupHistoryDo
	Order(conds ...field.Expr) IBackupHistoryDo
	Distinct(cols ...field.Expr) IBackupHistoryDo
	Omit(cols ...field.Expr) IBackupHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IBackupHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBackupHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBackupHistoryDo
	Group(cols ...field.Expr) IBackupHistoryDo
	Having(conds ...gen.Condition) IBackupHistoryDo
	Limit(limit int) IBackupHistoryDo
	Offset(offset int) IBackupHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupHistoryDo
	Unscoped() IBackupHistoryDo
	Create(values ...*model.BackupHistory) error
	CreateInBatches(values []*model.BackupHistory, batchSize int) error
	Save(values ...*model.BackupHistory) error
	First() (*model.BackupHistory, error)
	Take() (*model.BackupHistory, error)
	Last() (*model.BackupHistory, error)
	Find() ([]*model.BackupHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupHistory, err error)
	FindInBatches(result *[]*model.BackupHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BackupHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBackupHistoryDo
	Assign(attrs ...field.AssignExpr) IBackupHistoryDo
	Joins(fields ...field.RelationField) IBackupHistoryDo
	Preload(fields ...field.RelationField) IBackupHistoryDo
	FirstOrInit() (*model.BackupHistory, error)
	FirstOrCreate() (*model.BackupHistory, error)
	FindByPage(offset int, limit int) (result []*model.BackupHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBackupHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b backupHistoryDo) Debug() IBackupHistoryDo {
	return b.withDO(b.DO.Debug())
}

func (b backupHistoryDo) WithContext(ctx context.Context) IBackupHistoryDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b backupHistoryDo) ReadDB() IBackupHistoryDo {
	return b.Clauses(dbresolver.Read)
}

func (b backupHistoryDo) WriteDB() IBackupHistoryDo {
	return b.Clauses(dbresolver.Write)
}

func (b backupHistoryDo) Session(config *gorm.Session) IBackupHistoryDo {
	return b.withDO(b.DO.Session(config))
}

func (b backupHistoryDo) Clauses(conds ...clause.Expression) IBackupHistoryDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b backupHistoryDo) Returning(value interface{}, columns ...string) IBackupHistoryDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b backupHistoryDo) Not(conds ...gen.Condition) IBackupHistoryDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b backupHistoryDo) Or(conds ...gen.Condition) IBackupHistoryDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b backupHistoryDo) Select(conds ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b backupHistoryDo) Where(conds ...gen.Condition) IBackupHistoryDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b backupHistoryDo) Order(conds ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b backupHistoryDo) Distinct(cols ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b backupHistoryDo) Omit(cols ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b backupHistoryDo) Join(table schema.Tabler, on ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b backupHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b backupHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b backupHistoryDo) Group(cols ...field.Expr) IBackupHistoryDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b backupHistoryDo) Having(conds ...gen.Condition) IBackupHistoryDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b backupHistoryDo) Limit(limit int) IBackupHistoryDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b backupHistoryDo) Offset(offset int) IBackupHistoryDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b backupHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupHistoryDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b backupHistoryDo) Unscoped() IBackupHistoryDo {
	return b.withDO(b.DO.Unscoped())
}

func (b backupHistoryDo) Create(values ...*model.BackupHistory) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b backupHistoryDo) CreateInBatches(values []*model.BackupHistory, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b backupHistoryDo) Save(values ...*model.BackupHistory) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b backupHistoryDo) First() (*model.BackupHistory, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupHistory), nil
	}
}

func (b backupHistoryDo) Take() (*model.BackupHistory, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupHistory), nil
	}
}

func (b backupHistoryDo) Last() (*model.BackupHistory, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupHistory), nil
	}
}

func (b backupHistoryDo) Find() ([]*model.BackupHistory, error) {
	result, err := b.DO.Find()
	return result.([]*model.BackupHistory), err
}

func (b backupHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupHistory, err error) {
	buf := make([]*model.BackupHistory, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b backupHistoryDo) FindInBatches(result *[]*model.BackupHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b backupHistoryDo) Attrs(attrs ...field.AssignExpr) IBackupHistoryDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b backupHistoryDo) Assign(attrs ...field.AssignExpr) IBackupHistoryDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b backupHistoryDo) Joins(fields ...field.RelationField) IBackupHistoryDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b backupHistoryDo) Preload(fields ...field.RelationField) IBackupHistoryDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b backupHistoryDo) FirstOrInit() (*model.BackupHistory, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupHistory), nil
	}
}

func (b backupHistoryDo) FirstOrCreate() (*model.BackupHistory, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupHistory), nil
	}
}

func (b backupHistoryDo) FindByPage(offset int, limit int) (result []*model.BackupHistory, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b backupHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b backupHistoryDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b backupHistoryDo) Delete(models ...*model.BackupHistory) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *backupHistoryDo) withDO(do gen.Dao) *backupHistoryDo {
	b.DO = *do.(*gen.DO)
	return b
}
