// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newFriendRelationship(db *gorm.DB, opts ...gen.DOOption) friendRelationship {
	_friendRelationship := friendRelationship{}

	_friendRelationship.friendRelationshipDo.UseDB(db, opts...)
	_friendRelationship.friendRelationshipDo.UseModel(&model.FriendRelationship{})

	tableName := _friendRelationship.friendRelationshipDo.TableName()
	_friendRelationship.ALL = field.NewAsterisk(tableName)
	_friendRelationship.ID = field.NewInt64(tableName, "id")
	_friendRelationship.UID = field.NewInt64(tableName, "uid")
	_friendRelationship.FriendUID = field.NewInt64(tableName, "friend_uid")
	_friendRelationship.Status = field.NewString(tableName, "status")
	_friendRelationship.CreatedAt = field.NewField(tableName, "created_at")
	_friendRelationship.UpdatedAt = field.NewField(tableName, "updated_at")
	_friendRelationship.DeletedAt = field.NewField(tableName, "deleted_at")

	_friendRelationship.fillFieldMap()

	return _friendRelationship
}

type friendRelationship struct {
	friendRelationshipDo friendRelationshipDo

	ALL       field.Asterisk
	ID        field.Int64
	UID       field.Int64
	FriendUID field.Int64
	Status    field.String
	CreatedAt field.Field
	UpdatedAt field.Field
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (f friendRelationship) Table(newTableName string) *friendRelationship {
	f.friendRelationshipDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f friendRelationship) As(alias string) *friendRelationship {
	f.friendRelationshipDo.DO = *(f.friendRelationshipDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *friendRelationship) updateTableName(table string) *friendRelationship {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UID = field.NewInt64(table, "uid")
	f.FriendUID = field.NewInt64(table, "friend_uid")
	f.Status = field.NewString(table, "status")
	f.CreatedAt = field.NewField(table, "created_at")
	f.UpdatedAt = field.NewField(table, "updated_at")
	f.DeletedAt = field.NewField(table, "deleted_at")

	f.fillFieldMap()

	return f
}

func (f *friendRelationship) WithContext(ctx context.Context) IFriendRelationshipDo {
	return f.friendRelationshipDo.WithContext(ctx)
}

func (f friendRelationship) TableName() string { return f.friendRelationshipDo.TableName() }

func (f friendRelationship) Alias() string { return f.friendRelationshipDo.Alias() }

func (f friendRelationship) Columns(cols ...field.Expr) gen.Columns {
	return f.friendRelationshipDo.Columns(cols...)
}

func (f *friendRelationship) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *friendRelationship) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.ID
	f.fieldMap["uid"] = f.UID
	f.fieldMap["friend_uid"] = f.FriendUID
	f.fieldMap["status"] = f.Status
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
}

func (f friendRelationship) clone(db *gorm.DB) friendRelationship {
	f.friendRelationshipDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f friendRelationship) replaceDB(db *gorm.DB) friendRelationship {
	f.friendRelationshipDo.ReplaceDB(db)
	return f
}

type friendRelationshipDo struct{ gen.DO }

type IFriendRelationshipDo interface {
	gen.SubQuery
	Debug() IFriendRelationshipDo
	WithContext(ctx context.Context) IFriendRelationshipDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFriendRelationshipDo
	WriteDB() IFriendRelationshipDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFriendRelationshipDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFriendRelationshipDo
	Not(conds ...gen.Condition) IFriendRelationshipDo
	Or(conds ...gen.Condition) IFriendRelationshipDo
	Select(conds ...field.Expr) IFriendRelationshipDo
	Where(conds ...gen.Condition) IFriendRelationshipDo
	Order(conds ...field.Expr) IFriendRelationshipDo
	Distinct(cols ...field.Expr) IFriendRelationshipDo
	Omit(cols ...field.Expr) IFriendRelationshipDo
	Join(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo
	Group(cols ...field.Expr) IFriendRelationshipDo
	Having(conds ...gen.Condition) IFriendRelationshipDo
	Limit(limit int) IFriendRelationshipDo
	Offset(offset int) IFriendRelationshipDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFriendRelationshipDo
	Unscoped() IFriendRelationshipDo
	Create(values ...*model.FriendRelationship) error
	CreateInBatches(values []*model.FriendRelationship, batchSize int) error
	Save(values ...*model.FriendRelationship) error
	First() (*model.FriendRelationship, error)
	Take() (*model.FriendRelationship, error)
	Last() (*model.FriendRelationship, error)
	Find() ([]*model.FriendRelationship, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FriendRelationship, err error)
	FindInBatches(result *[]*model.FriendRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FriendRelationship) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFriendRelationshipDo
	Assign(attrs ...field.AssignExpr) IFriendRelationshipDo
	Joins(fields ...field.RelationField) IFriendRelationshipDo
	Preload(fields ...field.RelationField) IFriendRelationshipDo
	FirstOrInit() (*model.FriendRelationship, error)
	FirstOrCreate() (*model.FriendRelationship, error)
	FindByPage(offset int, limit int) (result []*model.FriendRelationship, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFriendRelationshipDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f friendRelationshipDo) Debug() IFriendRelationshipDo {
	return f.withDO(f.DO.Debug())
}

func (f friendRelationshipDo) WithContext(ctx context.Context) IFriendRelationshipDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f friendRelationshipDo) ReadDB() IFriendRelationshipDo {
	return f.Clauses(dbresolver.Read)
}

func (f friendRelationshipDo) WriteDB() IFriendRelationshipDo {
	return f.Clauses(dbresolver.Write)
}

func (f friendRelationshipDo) Session(config *gorm.Session) IFriendRelationshipDo {
	return f.withDO(f.DO.Session(config))
}

func (f friendRelationshipDo) Clauses(conds ...clause.Expression) IFriendRelationshipDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f friendRelationshipDo) Returning(value interface{}, columns ...string) IFriendRelationshipDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f friendRelationshipDo) Not(conds ...gen.Condition) IFriendRelationshipDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f friendRelationshipDo) Or(conds ...gen.Condition) IFriendRelationshipDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f friendRelationshipDo) Select(conds ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f friendRelationshipDo) Where(conds ...gen.Condition) IFriendRelationshipDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f friendRelationshipDo) Order(conds ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f friendRelationshipDo) Distinct(cols ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f friendRelationshipDo) Omit(cols ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f friendRelationshipDo) Join(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f friendRelationshipDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f friendRelationshipDo) RightJoin(table schema.Tabler, on ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f friendRelationshipDo) Group(cols ...field.Expr) IFriendRelationshipDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f friendRelationshipDo) Having(conds ...gen.Condition) IFriendRelationshipDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f friendRelationshipDo) Limit(limit int) IFriendRelationshipDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f friendRelationshipDo) Offset(offset int) IFriendRelationshipDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f friendRelationshipDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFriendRelationshipDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f friendRelationshipDo) Unscoped() IFriendRelationshipDo {
	return f.withDO(f.DO.Unscoped())
}

func (f friendRelationshipDo) Create(values ...*model.FriendRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f friendRelationshipDo) CreateInBatches(values []*model.FriendRelationship, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

func (f friendRelationshipDo) Save(values ...*model.FriendRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f friendRelationshipDo) First() (*model.FriendRelationship, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FriendRelationship), nil
	}
}

func (f friendRelationshipDo) Take() (*model.FriendRelationship, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FriendRelationship), nil
	}
}

func (f friendRelationshipDo) Last() (*model.FriendRelationship, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FriendRelationship), nil
	}
}

func (f friendRelationshipDo) Find() ([]*model.FriendRelationship, error) {
	result, err := f.DO.Find()
	return result.([]*model.FriendRelationship), err
}

func (f friendRelationshipDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FriendRelationship, err error) {
	buf := make([]*model.FriendRelationship, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f friendRelationshipDo) FindInBatches(result *[]*model.FriendRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f friendRelationshipDo) Attrs(attrs ...field.AssignExpr) IFriendRelationshipDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f friendRelationshipDo) Assign(attrs ...field.AssignExpr) IFriendRelationshipDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f friendRelationshipDo) Joins(fields ...field.RelationField) IFriendRelationshipDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f friendRelationshipDo) Preload(fields ...field.RelationField) IFriendRelationshipDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f friendRelationshipDo) FirstOrInit() (*model.FriendRelationship, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FriendRelationship), nil
	}
}

func (f friendRelationshipDo) FirstOrCreate() (*model.FriendRelationship, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FriendRelationship), nil
	}
}

func (f friendRelationshipDo) FindByPage(offset int, limit int) (result []*model.FriendRelationship, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f friendRelationshipDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f friendRelationshipDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f friendRelationshipDo) Delete(models ...*model.FriendRelationship) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *friendRelationshipDo) withDO(do gen.Dao) *friendRelationshipDo {
	f.DO = *do.(*gen.DO)
	return f
}
