// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newGitSyncConfig(db *gorm.DB, opts ...gen.DOOption) gitSyncConfig {
	_gitSyncConfig := gitSyncConfig{}

	_gitSyncConfig.gitSyncConfigDo.UseDB(db, opts...)
	_gitSyncConfig.gitSyncConfigDo.UseModel(&model.GitSyncConfig{})

	tableName := _gitSyncConfig.gitSyncConfigDo.TableName()
	_gitSyncConfig.ALL = field.NewAsterisk(tableName)
	_gitSyncConfig.ID = field.NewInt64(tableName, "id")
	_gitSyncConfig.UID = field.NewInt64(tableName, "uid")
	_gitSyncConfig.VaultID = field.NewInt64(tableName, "vault_id")
	_gitSyncConfig.RepoURL = field.NewString(tableName, "repo_url")
	_gitSyncConfig.Username = field.NewString(tableName, "username")
	_gitSyncConfig.Password = field.NewString(tableName, "password")
	_gitSyncConfig.Branch = field.NewString(tableName, "branch")
	_gitSyncConfig.IsEnabled = field.NewInt64(tableName, "is_enabled")
	_gitSyncConfig.Delay = field.NewInt64(tableName, "delay")
	_gitSyncConfig.RetentionDays = field.NewInt64(tableName, "retention_days")
	_gitSyncConfig.LastSyncTime = field.NewTime(tableName, "last_sync_time")
	_gitSyncConfig.LastStatus = field.NewInt64(tableName, "last_status")
	_gitSyncConfig.LastMessage = field.NewString(tableName, "last_message")
	_gitSyncConfig.IncludeConfig = field.NewInt64(tableName, "include_config")
	_gitSyncConfig.ConfigSyncRules = field.NewString(tableName, "config_sync_rules")
	_gitSyncConfig.CreatedAt = field.NewField(tableName, "created_at")
	_gitSyncConfig.UpdatedAt = field.NewField(tableName, "updated_at")

	_gitSyncConfig.fillFieldMap()

	return _gitSyncConfig
}

type gitSyncConfig struct {
	gitSyncConfigDo gitSyncConfigDo

	ALL             field.Asterisk
	ID              field.Int64
	UID             field.Int64
	VaultID         field.Int64
	RepoURL         field.String
	Username        field.String
	Password        field.String
	Branch          field.String
	IsEnabled       field.Int64
	Delay           field.Int64
	RetentionDays   field.Int64
	LastSyncTime    field.Time
	LastStatus      field.Int64
	LastMessage     field.String
	IncludeConfig   field.Int64
	ConfigSyncRules field.String
	CreatedAt       field.Field
	UpdatedAt       field.Field

	fieldMap map[string]field.Expr
}

func (g gitSyncConfig) Table(newTableName string) *gitSyncConfig {
	g.gitSyncConfigDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gitSyncConfig) As(alias string) *gitSyncConfig {
	g.gitSyncConfigDo.DO = *(g.gitSyncConfigDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gitSyncConfig) updateTableName(table string) *gitSyncConfig {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.UID = field.NewInt64(table, "uid")
	g.VaultID = field.NewInt64(table, "vault_id")
	g.RepoURL = field.NewString(table, "repo_url")
	g.Username = field.NewString(table, "username")
	g.Password = field.NewString(table, "password")
	g.Branch = field.NewString(table, "branch")
	g.IsEnabled = field.NewInt64(table, "is_enabled")
	g.Delay = field.NewInt64(table, "delay")
	g.RetentionDays = field.NewInt64(table, "retention_days")
	g.LastSyncTime = field.NewTime(table, "last_sync_time")
	g.LastStatus = field.NewInt64(table, "last_status")
	g.LastMessage = field.NewString(table, "last_message")
	g.IncludeConfig = field.NewInt64(table, "include_config")
	g.ConfigSyncRules = field.NewString(table, "config_sync_rules")
	g.CreatedAt = field.NewField(table, "created_at")
	g.UpdatedAt = field.NewField(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *gitSyncConfig) WithContext(ctx context.Context) IGitSyncConfigDo {
	return g.gitSyncConfigDo.WithContext(ctx)
}

func (g gitSyncConfig) TableName() string { return g.gitSyncConfigDo.TableName() }

func (g gitSyncConfig) Alias() string { return g.gitSyncConfigDo.Alias() }

func (g gitSyncConfig) Columns(cols ...field.Expr) gen.Columns {
	return g.gitSyncConfigDo.Columns(cols...)
}

func (g *gitSyncConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gitSyncConfig) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 17)
	g.fieldMap["id"] = g.ID
	g.fieldMap["uid"] = g.UID
	g.fieldMap["vault_id"] = g.VaultID
	g.fieldMap["repo_url"] = g.RepoURL
	g.fieldMap["username"] = g.Username
	g.fieldMap["password"] = g.Password
	g.fieldMap["branch"] = g.Branch
	g.fieldMap["is_enabled"] = g.IsEnabled
	g.fieldMap["delay"] = g.Delay
	g.fieldMap["retention_days"] = g.RetentionDays
	g.fieldMap["last_sync_time"] = g.LastSyncTime
	g.fieldMap["last_status"] = g.LastStatus
	g.fieldMap["last_message"] = g.LastMessage
	g.fieldMap["include_config"] = g.IncludeConfig
	g.fieldMap["config_sync_rules"] = g.ConfigSyncRules
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g gitSyncConfig) clone(db *gorm.DB) gitSyncConfig {
	g.gitSyncConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gitSyncConfig) replaceDB(db *gorm.DB) gitSyncConfig {
	g.gitSyncConfigDo.ReplaceDB(db)
	return g
}

type gitSyncConfigDo struct{ gen.DO }

type IGitSyncConfigDo interface {
	gen.SubQuery
	Debug() IGitSyncConfigDo
	WithContext(ctx context.Context) IGitSyncConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGitSyncConfigDo
	WriteDB() IGitSyncConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGitSyncConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGitSyncConfigDo
	Not(conds ...gen.Condition) IGitSyncConfigDo
	Or(conds ...gen.Condition) IGitSyncConfigDo
	Select(conds ...field.Expr) IGitSyncConfigDo
	Where(conds ...gen.Condition) IGitSyncConfigDo
	Order(conds ...field.Expr) IGitSyncConfigDo
	Distinct(cols ...field.Expr) IGitSyncConfigDo
	Omit(cols ...field.Expr) IGitSyncConfigDo
	Join(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo
	Group(cols ...field.Expr) IGitSyncConfigDo
	Having(conds ...gen.Condition) IGitSyncConfigDo
	Limit(limit int) IGitSyncConfigDo
	Offset(offset int) IGitSyncConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGitSyncConfigDo
	Unscoped() IGitSyncConfigDo
	Create(values ...*model.GitSyncConfig) error
	CreateInBatches(values []*model.GitSyncConfig, batchSize int) error
	Save(values ...*model.GitSyncConfig) error
	First() (*model.GitSyncConfig, error)
	Take() (*model.GitSyncConfig, error)
	Last() (*model.GitSyncConfig, error)
	Find() ([]*model.GitSyncConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GitSyncConfig, err error)
	FindInBatches(result *[]*model.GitSyncConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GitSyncConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGitSyncConfigDo
	Assign(attrs ...field.AssignExpr) IGitSyncConfigDo
	Joins(fields ...field.RelationField) IGitSyncConfigDo
	Preload(fields ...field.RelationField) IGitSyncConfigDo
	FirstOrInit() (*model.GitSyncConfig, error)
	FirstOrCreate() (*model.GitSyncConfig, error)
	FindByPage(offset int, limit int) (result []*model.GitSyncConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGitSyncConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gitSyncConfigDo) Debug() IGitSyncConfigDo {
	return g.withDO(g.DO.Debug())
}

func (g gitSyncConfigDo) WithContext(ctx context.Context) IGitSyncConfigDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gitSyncConfigDo) ReadDB() IGitSyncConfigDo {
	return g.Clauses(dbresolver.Read)
}

func (g gitSyncConfigDo) WriteDB() IGitSyncConfigDo {
	return g.Clauses(dbresolver.Write)
}

func (g gitSyncConfigDo) Session(config *gorm.Session) IGitSyncConfigDo {
	return g.withDO(g.DO.Session(config))
}

func (g gitSyncConfigDo) Clauses(conds ...clause.Expression) IGitSyncConfigDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gitSyncConfigDo) Returning(value interface{}, columns ...string) IGitSyncConfigDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gitSyncConfigDo) Not(conds ...gen.Condition) IGitSyncConfigDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gitSyncConfigDo) Or(conds ...gen.Condition) IGitSyncConfigDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gitSyncConfigDo) Select(conds ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gitSyncConfigDo) Where(conds ...gen.Condition) IGitSyncConfigDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gitSyncConfigDo) Order(conds ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gitSyncConfigDo) Distinct(cols ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gitSyncConfigDo) Omit(cols ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gitSyncConfigDo) Join(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gitSyncConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gitSyncConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gitSyncConfigDo) Group(cols ...field.Expr) IGitSyncConfigDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gitSyncConfigDo) Having(conds ...gen.Condition) IGitSyncConfigDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gitSyncConfigDo) Limit(limit int) IGitSyncConfigDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gitSyncConfigDo) Offset(offset int) IGitSyncConfigDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gitSyncConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGitSyncConfigDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gitSyncConfigDo) Unscoped() IGitSyncConfigDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gitSyncConfigDo) Create(values ...*model.GitSyncConfig) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gitSyncConfigDo) CreateInBatches(values []*model.GitSyncConfig, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gitSyncConfigDo) Save(values ...*model.GitSyncConfig) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gitSyncConfigDo) First() (*model.GitSyncConfig, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncConfig), nil
	}
}

func (g gitSyncConfigDo) Take() (*model.GitSyncConfig, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncConfig), nil
	}
}

func (g gitSyncConfigDo) Last() (*model.GitSyncConfig, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncConfig), nil
	}
}

func (g gitSyncConfigDo) Find() ([]*model.GitSyncConfig, error) {
	result, err := g.DO.Find()
	return result.([]*model.GitSyncConfig), err
}

func (g gitSyncConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GitSyncConfig, err error) {
	buf := make([]*model.GitSyncConfig, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gitSyncConfigDo) FindInBatches(result *[]*model.GitSyncConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gitSyncConfigDo) Attrs(attrs ...field.AssignExpr) IGitSyncConfigDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gitSyncConfigDo) Assign(attrs ...field.AssignExpr) IGitSyncConfigDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gitSyncConfigDo) Joins(fields ...field.RelationField) IGitSyncConfigDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gitSyncConfigDo) Preload(fields ...field.RelationField) IGitSyncConfigDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gitSyncConfigDo) FirstOrInit() (*model.GitSyncConfig, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncConfig), nil
	}
}

func (g gitSyncConfigDo) FirstOrCreate() (*model.GitSyncConfig, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncConfig), nil
	}
}

func (g gitSyncConfigDo) FindByPage(offset int, limit int) (result []*model.GitSyncConfig, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gitSyncConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gitSyncConfigDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gitSyncConfigDo) Delete(models ...*model.GitSyncConfig) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gitSyncConfigDo) withDO(do gen.Dao) *gitSyncConfigDo {
	g.DO = *do.(*gen.DO)
	return g
}
