// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newNoteHistory(db *gorm.DB, opts ...gen.DOOption) noteHistory {
	_noteHistory := noteHistory{}

	_noteHistory.noteHistoryDo.UseDB(db, opts...)
	_noteHistory.noteHistoryDo.UseModel(&model.NoteHistory{})

	tableName := _noteHistory.noteHistoryDo.TableName()
	_noteHistory.ALL = field.NewAsterisk(tableName)
	_noteHistory.ID = field.NewInt64(tableName, "id")
	_noteHistory.NoteID = field.NewInt64(tableName, "note_id")
	_noteHistory.VaultID = field.NewInt64(tableName, "vault_id")
	_noteHistory.Path = field.NewString(tableName, "path")
	_noteHistory.Content = field.NewString(tableName, "content")
	_noteHistory.ContentHash = field.NewString(tableName, "content_hash")
	_noteHistory.DiffPatch = field.NewString(tableName, "diff_patch")
	_noteHistory.ClientName = field.NewString(tableName, "client_name")
	_noteHistory.ClientType = field.NewString(tableName, "client_type")
	_noteHistory.ClientVersion = field.NewString(tableName, "client_version")
	_noteHistory.Version = field.NewInt64(tableName, "version")
	_noteHistory.CreatedAt = field.NewField(tableName, "created_at")
	_noteHistory.UpdatedAt = field.NewField(tableName, "updated_at")

	_noteHistory.fillFieldMap()

	return _noteHistory
}

type noteHistory struct {
	noteHistoryDo noteHistoryDo

	ALL           field.Asterisk
	ID            field.Int64
	NoteID        field.Int64
	VaultID       field.Int64
	Path          field.String
	Content       field.String
	ContentHash   field.String
	DiffPatch     field.String
	ClientName    field.String
	ClientType    field.String
	ClientVersion field.String
	Version       field.Int64
	CreatedAt     field.Field
	UpdatedAt     field.Field

	fieldMap map[string]field.Expr
}

func (n noteHistory) Table(newTableName string) *noteHistory {
	n.noteHistoryDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteHistory) As(alias string) *noteHistory {
	n.noteHistoryDo.DO = *(n.noteHistoryDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteHistory) updateTableName(table string) *noteHistory {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NoteID = field.NewInt64(table, "note_id")
	n.VaultID = field.NewInt64(table, "vault_id")
	n.Path = field.NewString(table, "path")
	n.Content = field.NewString(table, "content")
	n.ContentHash = field.NewString(table, "content_hash")
	n.DiffPatch = field.NewString(table, "diff_patch")
	n.ClientName = field.NewString(table, "client_name")
	n.ClientType = field.NewString(table, "client_type")
	n.ClientVersion = field.NewString(table, "client_version")
	n.Version = field.NewInt64(table, "version")
	n.CreatedAt = field.NewField(table, "created_at")
	n.UpdatedAt = field.NewField(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *noteHistory) WithContext(ctx context.Context) INoteHistoryDo {
	return n.noteHistoryDo.WithContext(ctx)
}

func (n noteHistory) TableName() string { return n.noteHistoryDo.TableName() }

func (n noteHistory) Alias() string { return n.noteHistoryDo.Alias() }

func (n noteHistory) Columns(cols ...field.Expr) gen.Columns { return n.noteHistoryDo.Columns(cols...) }

func (n *noteHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteHistory) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["note_id"] = n.NoteID
	n.fieldMap["vault_id"] = n.VaultID
	n.fieldMap["path"] = n.Path
	n.fieldMap["content"] = n.Content
	n.fieldMap["content_hash"] = n.ContentHash
	n.fieldMap["diff_patch"] = n.DiffPatch
	n.fieldMap["client_name"] = n.ClientName
	n.fieldMap["client_type"] = n.ClientType
	n.fieldMap["client_version"] = n.ClientVersion
	n.fieldMap["version"] = n.Version
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n noteHistory) clone(db *gorm.DB) noteHistory {
	n.noteHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteHistory) replaceDB(db *gorm.DB) noteHistory {
	n.noteHistoryDo.ReplaceDB(db)
	return n
}

type noteHistoryDo struct{ gen.DO }

type INoteHistoryDo interface {
	gen.SubQuery
	Debug() INoteHistoryDo
	WithContext(ctx context.Context) INoteHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteHistoryDo
	WriteDB() INoteHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteHistoryDo
	Not(conds ...gen.Condition) INoteHistoryDo
	Or(conds ...gen.Condition) INoteHistoryDo
	Select(conds ...field.Expr) INoteHistoryDo
	Where(conds ...gen.Condition) INoteHistoryDo
	Order(conds ...field.Expr) INoteHistoryDo
	Distinct(cols ...field.Expr) INoteHistoryDo
	Omit(cols ...field.Expr) INoteHistoryDo
	Join(table schema.Tabler, on ...field.Expr) INoteHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteHistoryDo
	Group(cols ...field.Expr) INoteHistoryDo
	Having(conds ...gen.Condition) INoteHistoryDo
	Limit(limit int) INoteHistoryDo
	Offset(offset int) INoteHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteHistoryDo
	Unscoped() INoteHistoryDo
	Create(values ...*model.NoteHistory) error
	CreateInBatches(values []*model.NoteHistory, batchSize int) error
	Save(values ...*model.NoteHistory) error
	First() (*model.NoteHistory, error)
	Take() (*model.NoteHistory, error)
	Last() (*model.NoteHistory, error)
	Find() ([]*model.NoteHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteHistory, err error)
	FindInBatches(result *[]*model.NoteHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteHistoryDo
	Assign(attrs ...field.AssignExpr) INoteHistoryDo
	Joins(fields ...field.RelationField) INoteHistoryDo
	Preload(fields ...field.RelationField) INoteHistoryDo
	FirstOrInit() (*model.NoteHistory, error)
	FirstOrCreate() (*model.NoteHistory, error)
	FindByPage(offset int, limit int) (result []*model.NoteHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteHistoryDo) Debug() INoteHistoryDo {
	return n.withDO(n.DO.Debug())
}

func (n noteHistoryDo) WithContext(ctx context.Context) INoteHistoryDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteHistoryDo) ReadDB() INoteHistoryDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteHistoryDo) WriteDB() INoteHistoryDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteHistoryDo) Session(config *gorm.Session) INoteHistoryDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteHistoryDo) Clauses(conds ...clause.Expression) INoteHistoryDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteHistoryDo) Returning(value interface{}, columns ...string) INoteHistoryDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteHistoryDo) Not(conds ...gen.Condition) INoteHistoryDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteHistoryDo) Or(conds ...gen.Condition) INoteHistoryDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteHistoryDo) Select(conds ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteHistoryDo) Where(conds ...gen.Condition) INoteHistoryDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteHistoryDo) Order(conds ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteHistoryDo) Distinct(cols ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteHistoryDo) Omit(cols ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteHistoryDo) Join(table schema.Tabler, on ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteHistoryDo) Group(cols ...field.Expr) INoteHistoryDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteHistoryDo) Having(conds ...gen.Condition) INoteHistoryDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteHistoryDo) Limit(limit int) INoteHistoryDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteHistoryDo) Offset(offset int) INoteHistoryDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteHistoryDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteHistoryDo) Unscoped() INoteHistoryDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteHistoryDo) Create(values ...*model.NoteHistory) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteHistoryDo) CreateInBatches(values []*model.NoteHistory, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteHistoryDo) Save(values ...*model.NoteHistory) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteHistoryDo) First() (*model.NoteHistory, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteHistory), nil
	}
}

func (n noteHistoryDo) Take() (*model.NoteHistory, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteHistory), nil
	}
}

func (n noteHistoryDo) Last() (*model.NoteHistory, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteHistory), nil
	}
}

func (n noteHistoryDo) Find() ([]*model.NoteHistory, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteHistory), err
}

func (n noteHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteHistory, err error) {
	buf := make([]*model.NoteHistory, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteHistoryDo) FindInBatches(result *[]*model.NoteHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteHistoryDo) Attrs(attrs ...field.AssignExpr) INoteHistoryDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteHistoryDo) Assign(attrs ...field.AssignExpr) INoteHistoryDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteHistoryDo) Joins(fields ...field.RelationField) INoteHistoryDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteHistoryDo) Preload(fields ...field.RelationField) INoteHistoryDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteHistoryDo) FirstOrInit() (*model.NoteHistory, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteHistory), nil
	}
}

func (n noteHistoryDo) FirstOrCreate() (*model.NoteHistory, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteHistory), nil
	}
}

func (n noteHistoryDo) FindByPage(offset int, limit int) (result []*model.NoteHistory, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteHistoryDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteHistoryDo) Delete(models ...*model.NoteHistory) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteHistoryDo) withDO(do gen.Dao) *noteHistoryDo {
	n.DO = *do.(*gen.DO)
	return n
}
