// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newNote(db *gorm.DB, opts ...gen.DOOption) note {
	_note := note{}

	_note.noteDo.UseDB(db, opts...)
	_note.noteDo.UseModel(&model.Note{})

	tableName := _note.noteDo.TableName()
	_note.ALL = field.NewAsterisk(tableName)
	_note.ID = field.NewInt64(tableName, "id")
	_note.VaultID = field.NewInt64(tableName, "vault_id")
	_note.Action = field.NewString(tableName, "action")
	_note.Rename = field.NewInt64(tableName, "rename")
	_note.FID = field.NewInt64(tableName, "fid")
	_note.Path = field.NewString(tableName, "path")
	_note.PathHash = field.NewString(tableName, "path_hash")
	_note.Content = field.NewString(tableName, "content")
	_note.ContentHash = field.NewString(tableName, "content_hash")
	_note.ContentLastSnapshot = field.NewString(tableName, "content_last_snapshot")
	_note.ContentLastSnapshotHash = field.NewString(tableName, "content_last_snapshot_hash")
	_note.Version = field.NewInt64(tableName, "version")
	_note.ClientName = field.NewString(tableName, "client_name")
	_note.ClientType = field.NewString(tableName, "client_type")
	_note.ClientVersion = field.NewString(tableName, "client_version")
	_note.Size = field.NewInt64(tableName, "size")
	_note.Ctime = field.NewInt64(tableName, "ctime")
	_note.Mtime = field.NewInt64(tableName, "mtime")
	_note.UpdatedTimestamp = field.NewInt64(tableName, "updated_timestamp")
	_note.CreatedAt = field.NewField(tableName, "created_at")
	_note.UpdatedAt = field.NewField(tableName, "updated_at")

	_note.fillFieldMap()

	return _note
}

type note struct {
	noteDo noteDo

	ALL                     field.Asterisk
	ID                      field.Int64
	VaultID                 field.Int64
	Action                  field.String
	Rename                  field.Int64
	FID                     field.Int64
	Path                    field.String
	PathHash                field.String
	Content                 field.String
	ContentHash             field.String
	ContentLastSnapshot     field.String
	ContentLastSnapshotHash field.String
	Version                 field.Int64
	ClientName              field.String
	ClientType              field.String
	ClientVersion           field.String
	Size                    field.Int64
	Ctime                   field.Int64
	Mtime                   field.Int64
	UpdatedTimestamp        field.Int64
	CreatedAt               field.Field
	UpdatedAt               field.Field

	fieldMap map[string]field.Expr
}

func (n note) Table(newTableName string) *note {
	n.noteDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n note) As(alias string) *note {
	n.noteDo.DO = *(n.noteDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *note) updateTableName(table string) *note {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.VaultID = field.NewInt64(table, "vault_id")
	n.Action = field.NewString(table, "action")
	n.Rename = field.NewInt64(table, "rename")
	n.FID = field.NewInt64(table, "fid")
	n.Path = field.NewString(table, "path")
	n.PathHash = field.NewString(table, "path_hash")
	n.Content = field.NewString(table, "content")
	n.ContentHash = field.NewString(table, "content_hash")
	n.ContentLastSnapshot = field.NewString(table, "content_last_snapshot")
	n.ContentLastSnapshotHash = field.NewString(table, "content_last_snapshot_hash")
	n.Version = field.NewInt64(table, "version")
	n.ClientName = field.NewString(table, "client_name")
	n.ClientType = field.NewString(table, "client_type")
	n.ClientVersion = field.NewString(table, "client_version")
	n.Size = field.NewInt64(table, "size")
	n.Ctime = field.NewInt64(table, "ctime")
	n.Mtime = field.NewInt64(table, "mtime")
	n.UpdatedTimestamp = field.NewInt64(table, "updated_timestamp")
	n.CreatedAt = field.NewField(table, "created_at")
	n.UpdatedAt = field.NewField(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *note) WithContext(ctx context.Context) INoteDo { return n.noteDo.WithContext(ctx) }

func (n note) TableName() string { return n.noteDo.TableName() }

func (n note) Alias() string { return n.noteDo.Alias() }

func (n note) Columns(cols ...field.Expr) gen.Columns { return n.noteDo.Columns(cols...) }

func (n *note) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *note) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 21)
	n.fieldMap["id"] = n.ID
	n.fieldMap["vault_id"] = n.VaultID
	n.fieldMap["action"] = n.Action
	n.fieldMap["rename"] = n.Rename
	n.fieldMap["fid"] = n.FID
	n.fieldMap["path"] = n.Path
	n.fieldMap["path_hash"] = n.PathHash
	n.fieldMap["content"] = n.Content
	n.fieldMap["content_hash"] = n.ContentHash
	n.fieldMap["content_last_snapshot"] = n.ContentLastSnapshot
	n.fieldMap["content_last_snapshot_hash"] = n.ContentLastSnapshotHash
	n.fieldMap["version"] = n.Version
	n.fieldMap["client_name"] = n.ClientName
	n.fieldMap["client_type"] = n.ClientType
	n.fieldMap["client_version"] = n.ClientVersion
	n.fieldMap["size"] = n.Size
	n.fieldMap["ctime"] = n.Ctime
	n.fieldMap["mtime"] = n.Mtime
	n.fieldMap["updated_timestamp"] = n.UpdatedTimestamp
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n note) clone(db *gorm.DB) note {
	n.noteDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n note) replaceDB(db *gorm.DB) note {
	n.noteDo.ReplaceDB(db)
	return n
}

type noteDo struct{ gen.DO }

type INoteDo interface {
	gen.SubQuery
	Debug() INoteDo
	WithContext(ctx context.Context) INoteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteDo
	WriteDB() INoteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteDo
	Not(conds ...gen.Condition) INoteDo
	Or(conds ...gen.Condition) INoteDo
	Select(conds ...field.Expr) INoteDo
	Where(conds ...gen.Condition) INoteDo
	Order(conds ...field.Expr) INoteDo
	Distinct(cols ...field.Expr) INoteDo
	Omit(cols ...field.Expr) INoteDo
	Join(table schema.Tabler, on ...field.Expr) INoteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteDo
	Group(cols ...field.Expr) INoteDo
	Having(conds ...gen.Condition) INoteDo
	Limit(limit int) INoteDo
	Offset(offset int) INoteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteDo
	Unscoped() INoteDo
	Create(values ...*model.Note) error
	CreateInBatches(values []*model.Note, batchSize int) error
	Save(values ...*model.Note) error
	First() (*model.Note, error)
	Take() (*model.Note, error)
	Last() (*model.Note, error)
	Find() ([]*model.Note, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Note, err error)
	FindInBatches(result *[]*model.Note, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Note) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteDo
	Assign(attrs ...field.AssignExpr) INoteDo
	Joins(fields ...field.RelationField) INoteDo
	Preload(fields ...field.RelationField) INoteDo
	FirstOrInit() (*model.Note, error)
	FirstOrCreate() (*model.Note, error)
	FindByPage(offset int, limit int) (result []*model.Note, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteDo) Debug() INoteDo {
	return n.withDO(n.DO.Debug())
}

func (n noteDo) WithContext(ctx context.Context) INoteDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteDo) ReadDB() INoteDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteDo) WriteDB() INoteDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteDo) Session(config *gorm.Session) INoteDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteDo) Clauses(conds ...clause.Expression) INoteDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteDo) Returning(value interface{}, columns ...string) INoteDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteDo) Not(conds ...gen.Condition) INoteDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteDo) Or(conds ...gen.Condition) INoteDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteDo) Select(conds ...field.Expr) INoteDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteDo) Where(conds ...gen.Condition) INoteDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteDo) Order(conds ...field.Expr) INoteDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteDo) Distinct(cols ...field.Expr) INoteDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteDo) Omit(cols ...field.Expr) INoteDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteDo) Join(table schema.Tabler, on ...field.Expr) INoteDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteDo) Group(cols ...field.Expr) INoteDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteDo) Having(conds ...gen.Condition) INoteDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteDo) Limit(limit int) INoteDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteDo) Offset(offset int) INoteDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteDo) Unscoped() INoteDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteDo) Create(values ...*model.Note) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteDo) CreateInBatches(values []*model.Note, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteDo) Save(values ...*model.Note) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteDo) First() (*model.Note, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Note), nil
	}
}

func (n noteDo) Take() (*model.Note, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Note), nil
	}
}

func (n noteDo) Last() (*model.Note, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Note), nil
	}
}

func (n noteDo) Find() ([]*model.Note, error) {
	result, err := n.DO.Find()
	return result.([]*model.Note), err
}

func (n noteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Note, err error) {
	buf := make([]*model.Note, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteDo) FindInBatches(result *[]*model.Note, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteDo) Attrs(attrs ...field.AssignExpr) INoteDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteDo) Assign(attrs ...field.AssignExpr) INoteDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteDo) Joins(fields ...field.RelationField) INoteDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteDo) Preload(fields ...field.RelationField) INoteDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteDo) FirstOrInit() (*model.Note, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Note), nil
	}
}

func (n noteDo) FirstOrCreate() (*model.Note, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Note), nil
	}
}

func (n noteDo) FindByPage(offset int, limit int) (result []*model.Note, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteDo) Delete(models ...*model.Note) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteDo) withDO(do gen.Dao) *noteDo {
	n.DO = *do.(*gen.DO)
	return n
}
