// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newSyncLog(db *gorm.DB, opts ...gen.DOOption) syncLog {
	_syncLog := syncLog{}

	_syncLog.syncLogDo.UseDB(db, opts...)
	_syncLog.syncLogDo.UseModel(&model.SyncLog{})

	tableName := _syncLog.syncLogDo.TableName()
	_syncLog.ALL = field.NewAsterisk(tableName)
	_syncLog.ID = field.NewInt64(tableName, "id")
	_syncLog.UID = field.NewInt64(tableName, "uid")
	_syncLog.VaultID = field.NewInt64(tableName, "vault_id")
	_syncLog.Type = field.NewString(tableName, "type")
	_syncLog.Action = field.NewString(tableName, "action")
	_syncLog.ChangedFields = field.NewString(tableName, "changed_fields")
	_syncLog.Path = field.NewString(tableName, "path")
	_syncLog.PathHash = field.NewString(tableName, "path_hash")
	_syncLog.Size = field.NewInt64(tableName, "size")
	_syncLog.ClientName = field.NewString(tableName, "client_name")
	_syncLog.ClientType = field.NewString(tableName, "client_type")
	_syncLog.ClientVersion = field.NewString(tableName, "client_version")
	_syncLog.Status = field.NewInt64(tableName, "status")
	_syncLog.Message = field.NewString(tableName, "message")
	_syncLog.CreatedAt = field.NewField(tableName, "created_at")

	_syncLog.fillFieldMap()

	return _syncLog
}

type syncLog struct {
	syncLogDo syncLogDo

	ALL           field.Asterisk
	ID            field.Int64
	UID           field.Int64
	VaultID       field.Int64
	Type          field.String
	Action        field.String
	ChangedFields field.String
	Path          field.String
	PathHash      field.String
	Size          field.Int64
	ClientName    field.String
	ClientType    field.String
	ClientVersion field.String
	Status        field.Int64
	Message       field.String
	CreatedAt     field.Field

	fieldMap map[string]field.Expr
}

func (s syncLog) Table(newTableName string) *syncLog {
	s.syncLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncLog) As(alias string) *syncLog {
	s.syncLogDo.DO = *(s.syncLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncLog) updateTableName(table string) *syncLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UID = field.NewInt64(table, "uid")
	s.VaultID = field.NewInt64(table, "vault_id")
	s.Type = field.NewString(table, "type")
	s.Action = field.NewString(table, "action")
	s.ChangedFields = field.NewString(table, "changed_fields")
	s.Path = field.NewString(table, "path")
	s.PathHash = field.NewString(table, "path_hash")
	s.Size = field.NewInt64(table, "size")
	s.ClientName = field.NewString(table, "client_name")
	s.ClientType = field.NewString(table, "client_type")
	s.ClientVersion = field.NewString(table, "client_version")
	s.Status = field.NewInt64(table, "status")
	s.Message = field.NewString(table, "message")
	s.CreatedAt = field.NewField(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *syncLog) WithContext(ctx context.Context) ISyncLogDo { return s.syncLogDo.WithContext(ctx) }

func (s syncLog) TableName() string { return s.syncLogDo.TableName() }

func (s syncLog) Alias() string { return s.syncLogDo.Alias() }

func (s syncLog) Columns(cols ...field.Expr) gen.Columns { return s.syncLogDo.Columns(cols...) }

func (s *syncLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["uid"] = s.UID
	s.fieldMap["vault_id"] = s.VaultID
	s.fieldMap["type"] = s.Type
	s.fieldMap["action"] = s.Action
	s.fieldMap["changed_fields"] = s.ChangedFields
	s.fieldMap["path"] = s.Path
	s.fieldMap["path_hash"] = s.PathHash
	s.fieldMap["size"] = s.Size
	s.fieldMap["client_name"] = s.ClientName
	s.fieldMap["client_type"] = s.ClientType
	s.fieldMap["client_version"] = s.ClientVersion
	s.fieldMap["status"] = s.Status
	s.fieldMap["message"] = s.Message
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s syncLog) clone(db *gorm.DB) syncLog {
	s.syncLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncLog) replaceDB(db *gorm.DB) syncLog {
	s.syncLogDo.ReplaceDB(db)
	return s
}

type syncLogDo struct{ gen.DO }

type ISyncLogDo interface {
	gen.SubQuery
	Debug() ISyncLogDo
	WithContext(ctx context.Context) ISyncLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISyncLogDo
	WriteDB() ISyncLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISyncLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISyncLogDo
	Not(conds ...gen.Condition) ISyncLogDo
	Or(conds ...gen.Condition) ISyncLogDo
	Select(conds ...field.Expr) ISyncLogDo
	Where(conds ...gen.Condition) ISyncLogDo
	Order(conds ...field.Expr) ISyncLogDo
	Distinct(cols ...field.Expr) ISyncLogDo
	Omit(cols ...field.Expr) ISyncLogDo
	Join(table schema.Tabler, on ...field.Expr) ISyncLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISyncLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISyncLogDo
	Group(cols ...field.Expr) ISyncLogDo
	Having(conds ...gen.Condition) ISyncLogDo
	Limit(limit int) ISyncLogDo
	Offset(offset int) ISyncLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncLogDo
	Unscoped() ISyncLogDo
	Create(values ...*model.SyncLog) error
	CreateInBatches(values []*model.SyncLog, batchSize int) error
	Save(values ...*model.SyncLog) error
	First() (*model.SyncLog, error)
	Take() (*model.SyncLog, error)
	Last() (*model.SyncLog, error)
	Find() ([]*model.SyncLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SyncLog, err error)
	FindInBatches(result *[]*model.SyncLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SyncLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISyncLogDo
	Assign(attrs ...field.AssignExpr) ISyncLogDo
	Joins(fields ...field.RelationField) ISyncLogDo
	Preload(fields ...field.RelationField) ISyncLogDo
	FirstOrInit() (*model.SyncLog, error)
	FirstOrCreate() (*model.SyncLog, error)
	FindByPage(offset int, limit int) (result []*model.SyncLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISyncLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s syncLogDo) Debug() ISyncLogDo {
	return s.withDO(s.DO.Debug())
}

func (s syncLogDo) WithContext(ctx context.Context) ISyncLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncLogDo) ReadDB() ISyncLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncLogDo) WriteDB() ISyncLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncLogDo) Session(config *gorm.Session) ISyncLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncLogDo) Clauses(conds ...clause.Expression) ISyncLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncLogDo) Returning(value interface{}, columns ...string) ISyncLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncLogDo) Not(conds ...gen.Condition) ISyncLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncLogDo) Or(conds ...gen.Condition) ISyncLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncLogDo) Select(conds ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncLogDo) Where(conds ...gen.Condition) ISyncLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncLogDo) Order(conds ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncLogDo) Distinct(cols ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncLogDo) Omit(cols ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncLogDo) Join(table schema.Tabler, on ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncLogDo) Group(cols ...field.Expr) ISyncLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncLogDo) Having(conds ...gen.Condition) ISyncLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncLogDo) Limit(limit int) ISyncLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncLogDo) Offset(offset int) ISyncLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncLogDo) Unscoped() ISyncLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncLogDo) Create(values ...*model.SyncLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncLogDo) CreateInBatches(values []*model.SyncLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncLogDo) Save(values ...*model.SyncLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncLogDo) First() (*model.SyncLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncLog), nil
	}
}

func (s syncLogDo) Take() (*model.SyncLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncLog), nil
	}
}

func (s syncLogDo) Last() (*model.SyncLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncLog), nil
	}
}

func (s syncLogDo) Find() ([]*model.SyncLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SyncLog), err
}

func (s syncLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SyncLog, err error) {
	buf := make([]*model.SyncLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncLogDo) FindInBatches(result *[]*model.SyncLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncLogDo) Attrs(attrs ...field.AssignExpr) ISyncLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncLogDo) Assign(attrs ...field.AssignExpr) ISyncLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncLogDo) Joins(fields ...field.RelationField) ISyncLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncLogDo) Preload(fields ...field.RelationField) ISyncLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncLogDo) FirstOrInit() (*model.SyncLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncLog), nil
	}
}

func (s syncLogDo) FirstOrCreate() (*model.SyncLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncLog), nil
	}
}

func (s syncLogDo) FindByPage(offset int, limit int) (result []*model.SyncLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncLogDo) Delete(models ...*model.SyncLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncLogDo) withDO(do gen.Dao) *syncLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
